/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddBooks.java
 *
 * Created on 14/06/2011, 16:13:26
 */

import javax.swing.JFileChooser;

/**
 *
 * @author msvolenski
 */
public class Book extends javax.swing.JPanel {
    private Santanbooks parent;
    /** Creates new form AddBooks */
    public Book(Santanbooks p) {
        this.parent = p;
        initComponents();
    }


    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        year = new javax.swing.JLabel();
        authors = new javax.swing.JLabel();
        edition = new javax.swing.JLabel();
        isbn = new javax.swing.JLabel();
        publisher = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        publisher1 = new javax.swing.JLabel();
        publisher3 = new javax.swing.JLabel();
        publisher4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        publisher5 = new javax.swing.JLabel();
        description2 = new javax.swing.JLabel();
        publisher6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pageTitle = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        year.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        year.setText("Ano:");

        authors.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        authors.setText("Autores:");

        edition.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        edition.setText("Edição:");

        isbn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        isbn.setText("ISBN:");

        publisher.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        publisher.setText("Editora:");

        description.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        description.setText("Resumo:");

        jLabel1.setText("<EDIÇÃO>");

        jLabel2.setText("<ANO>");

        publisher1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publisher1.setText("<EDITORA>");

        publisher3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publisher3.setText("<AUTORES>");

        publisher4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publisher4.setText("<RESUMO>");

        jLabel4.setText("<ISBN>");

        jLabel3.setText("<IMAGEM DO LIVRO>");

        description1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        description1.setText("Avaliações");

        publisher5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publisher5.setText("<AVALIAÇÕES>");

        description2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        description2.setText("Comentários");

        publisher6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        publisher6.setText("<COMENTÁRIOS>");

        jButton1.setText("Adicionar avaliação");

        jTextField1.setText("Digite seu comentário aqui");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pageTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageTitle.setText("<NOME DO LIVRO>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(529, 529, 529)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jButton2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(edition)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(year)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(publisher5)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(description1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton1))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(publisher6)
                                                .addComponent(description2))
                                            .addGap(154, 154, 154)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(description)
                                                .addGap(18, 18, 18)
                                                .addComponent(publisher4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(authors)
                                                    .addComponent(publisher))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(publisher3)
                                                    .addComponent(publisher1)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(isbn)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(pageTitle)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pageTitle)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(authors)
                                    .addComponent(publisher3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(publisher)
                                    .addComponent(publisher1)
                                    .addComponent(edition)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(isbn)
                                    .addComponent(jLabel4)
                                    .addComponent(year)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(description)
                            .addComponent(publisher4))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(description1)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(publisher5)
                        .addGap(36, 36, 36)
                        .addComponent(description2)
                        .addGap(18, 18, 18)
                        .addComponent(publisher6)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equalsIgnoreCase("Digite seu comentário aqui"))
            jTextField1.setText(null);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equalsIgnoreCase(""))
            jTextField1.setText("Digite seu comentário aqui");
    }//GEN-LAST:event_jTextField1FocusLost
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authors;
    private javax.swing.JLabel description;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel edition;
    private javax.swing.JLabel isbn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JLabel publisher;
    private javax.swing.JLabel publisher1;
    private javax.swing.JLabel publisher3;
    private javax.swing.JLabel publisher4;
    private javax.swing.JLabel publisher5;
    private javax.swing.JLabel publisher6;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
