/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditAccount.java
 *
 * Created on Jun 14, 2011, 4:58:47 PM
 */

/**
 *
 * @author ra073668
 */
public class EditProfile extends javax.swing.JPanel {
    private Santanbooks parent;
    /** Creates new form EditAccount */
    public EditProfile(Santanbooks p) {
        this.parent = p;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        userLabel1 = new javax.swing.JLabel();
        bdayLabel1 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        academicTitle1 = new javax.swing.JLabel();
        collegeLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionText1 = new javax.swing.JTextArea();
        maleButton1 = new javax.swing.JRadioButton();
        loginTitle1 = new javax.swing.JLabel();
        pwordLabel1 = new javax.swing.JLabel();
        yearText1 = new javax.swing.JTextField();
        pwordText1 = new javax.swing.JPasswordField();
        genderLabel1 = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        femaleButton1 = new javax.swing.JRadioButton();
        courseText1 = new javax.swing.JTextField();
        oldpwText1 = new javax.swing.JTextField();
        personalTitle1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        collegeText1 = new javax.swing.JTextField();
        bdayText1 = new javax.swing.JTextField();
        nameText1 = new javax.swing.JTextField();
        cancelButton1 = new javax.swing.JButton();
        emailText1 = new javax.swing.JTextField();
        saveButton1 = new javax.swing.JButton();
        repeatpwordLabel1 = new javax.swing.JLabel();
        repeatpwordText1 = new javax.swing.JPasswordField();
        courseLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        userLabel1.setText("Senha atual");
        add(userLabel1);
        userLabel1.setBounds(247, 449, 57, 14);

        bdayLabel1.setText("Nascimento");
        add(bdayLabel1);
        bdayLabel1.setBounds(444, 149, 55, 14);

        title1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title1.setText("Edite sua conta");
        add(title1);
        title1.setBounds(300, 45, 210, 29);

        academicTitle1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        academicTitle1.setText("Informações acadêmicas :");
        add(academicTitle1);
        academicTitle1.setBounds(200, 310, 190, 16);

        collegeLabel1.setText("Universidade");
        add(collegeLabel1);
        collegeLabel1.setBounds(195, 345, 62, 14);

        descriptionText1.setColumns(20);
        descriptionText1.setLineWrap(true);
        descriptionText1.setRows(5);
        jScrollPane2.setViewportView(descriptionText1);

        add(jScrollPane2);
        jScrollPane2.setBounds(195, 230, 416, 67);

        buttonGroup1.add(maleButton1);
        maleButton1.setText("Masc.");
        add(maleButton1);
        maleButton1.setBounds(290, 145, 53, 23);

        loginTitle1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        loginTitle1.setText("Altere sua senha:");
        add(loginTitle1);
        loginTitle1.setBounds(205, 415, 140, 16);

        pwordLabel1.setText("Nova Senha");
        add(pwordLabel1);
        pwordLabel1.setBounds(246, 481, 58, 14);
        add(yearText1);
        yearText1.setBounds(500, 380, 110, 20);
        add(pwordText1);
        pwordText1.setBounds(308, 478, 199, 20);

        genderLabel1.setText("Sexo");
        add(genderLabel1);
        genderLabel1.setBounds(200, 150, 24, 14);

        yearLabel1.setText("Ano");
        add(yearLabel1);
        yearLabel1.setBounds(475, 383, 19, 14);

        buttonGroup1.add(femaleButton1);
        femaleButton1.setText("Fem.");
        add(femaleButton1);
        femaleButton1.setBounds(235, 145, 49, 23);
        add(courseText1);
        courseText1.setBounds(260, 380, 204, 20);
        add(oldpwText1);
        oldpwText1.setBounds(308, 446, 199, 20);

        personalTitle1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        personalTitle1.setText("Informações pessoais:");
        add(personalTitle1);
        personalTitle1.setBounds(200, 90, 160, 16);

        nameLabel1.setText("Nome");
        add(nameLabel1);
        nameLabel1.setBounds(198, 119, 27, 14);

        descriptionLabel1.setText("Descreva-se em poucas linhas:");
        add(descriptionLabel1);
        descriptionLabel1.setBounds(200, 210, 148, 14);

        emailLabel1.setText("E-mail");
        add(emailLabel1);
        emailLabel1.setBounds(197, 182, 28, 14);
        add(collegeText1);
        collegeText1.setBounds(260, 340, 350, 20);
        add(bdayText1);
        bdayText1.setBounds(503, 146, 110, 20);

        nameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameText1ActionPerformed(evt);
            }
        });
        add(nameText1);
        nameText1.setBounds(229, 115, 384, 20);

        cancelButton1.setText("Cancelar");
        cancelButton1.setMaximumSize(new java.awt.Dimension(45, 30));
        cancelButton1.setMinimumSize(new java.awt.Dimension(45, 30));
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        add(cancelButton1);
        cancelButton1.setBounds(308, 540, 94, 23);
        add(emailText1);
        emailText1.setBounds(229, 179, 384, 20);

        saveButton1.setText("Salvar");
        saveButton1.setMaximumSize(new java.awt.Dimension(45, 30));
        saveButton1.setMinimumSize(new java.awt.Dimension(45, 30));
        add(saveButton1);
        saveButton1.setBounds(408, 540, 82, 23);

        repeatpwordLabel1.setText("Confirmar senha");
        add(repeatpwordLabel1);
        repeatpwordLabel1.setBounds(225, 512, 79, 14);
        add(repeatpwordText1);
        repeatpwordText1.setBounds(308, 509, 199, 20);

        courseLabel1.setText("Curso");
        add(courseLabel1);
        courseLabel1.setBounds(228, 383, 28, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        nameText1.setText(null);
        buttonGroup1.clearSelection();
        bdayText1.setText(null);
        emailText1.setText(null);
        collegeText1.setText(null);
        courseText1.setText(null);
        yearText1.setText(null);
        oldpwText1.setText(null);
        pwordText1.setText(null);
        repeatpwordText1.setText(null);
        descriptionText1.setText(null);
}//GEN-LAST:event_cancelButton1ActionPerformed

    private void nameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameText1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicTitle1;
    private javax.swing.JLabel bdayLabel1;
    private javax.swing.JTextField bdayText1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JLabel collegeLabel1;
    private javax.swing.JTextField collegeText1;
    private javax.swing.JLabel courseLabel1;
    private javax.swing.JTextField courseText1;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JTextArea descriptionText1;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailText1;
    private javax.swing.JRadioButton femaleButton1;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel loginTitle1;
    private javax.swing.JRadioButton maleButton1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameText1;
    private javax.swing.JTextField oldpwText1;
    private javax.swing.JLabel personalTitle1;
    private javax.swing.JLabel pwordLabel1;
    private javax.swing.JPasswordField pwordText1;
    private javax.swing.JLabel repeatpwordLabel1;
    private javax.swing.JPasswordField repeatpwordText1;
    private javax.swing.JButton saveButton1;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel yearLabel1;
    private javax.swing.JTextField yearText1;
    // End of variables declaration//GEN-END:variables

}
