/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Jun 14, 2011, 4:30:07 PM
 */

/**
 *
 * @author ra073668
 */
public class Home extends javax.swing.JPanel {
    private Santanbooks parent;

    /** Creates new form Login */
    public Home(Santanbooks p) {
        this.parent = p;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        autoList = new javax.swing.JList();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santanbooks.png"))); // NOI18N
        add(logo);
        logo.setBounds(130, 170, 540, 110);

        searchField.setFont(new java.awt.Font("Tahoma", 0, 14));
        add(searchField);
        searchField.setBounds(140, 300, 420, 30);

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 14));
        searchButton.setText("Buscar");
        add(searchButton);
        searchButton.setBounds(585, 300, 73, 30);

        autoList.setFont(new java.awt.Font("Tahoma", 0, 14));
        autoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "<AUTOCOMPLETE>", "<AUTOCOMPLETE>", "<AUTOCOMPLETE>", "<AUTOCOMPLETE>", "<AUTOCOMPLETE>", "<AUTOCOMPLETE>" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(autoList);

        add(jScrollPane1);
        jScrollPane1.setBounds(140, 330, 420, 154);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList autoList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

}
