import javax.swing.*;

public class Home extends JPanel {
    private Santanbooks parent;
    
    /** Creates new form Home */
    public Home(Santanbooks cardHolder) {
        initComponents();
        this.parent = cardHolder;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edBusca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblLivros = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        lblComentarios = new javax.swing.JLabel();
        edUsuario = new javax.swing.JTextField();
        edSenha = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Santanbooks.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(150, 310, 557, 117);

        jLabel2.setText("Buscar livros:");
        add(jLabel2);
        jLabel2.setBounds(400, 43, 64, 14);
        add(edBusca);
        edBusca.setBounds(470, 40, 260, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Login:");
        add(jLabel3);
        jLabel3.setBounds(51, 38, 43, 17);

        jLabel4.setText("Usuário:");
        add(jLabel4);
        jLabel4.setBounds(50, 93, 40, 14);

        jLabel5.setText("Senha:");
        add(jLabel5);
        jLabel5.setBounds(50, 123, 34, 14);

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setText("Login!");
        add(btnLogin);
        btnLogin.setBounds(90, 150, 108, 40);

        btnBuscar.setText("Buscar");
        add(btnBuscar);
        btnBuscar.setBounds(740, 38, 65, 23);

        jLabel6.setText("Usuários Ativos:");
        add(jLabel6);
        jLabel6.setBounds(490, 110, 90, 14);

        jLabel7.setText("Livros Cadastrados:");
        add(jLabel7);
        jLabel7.setBounds(490, 140, 100, 14);

        lblUsuarios.setText("0");
        add(lblUsuarios);
        lblUsuarios.setBounds(610, 110, 50, 14);

        lblLivros.setText("0");
        add(lblLivros);
        lblLivros.setBounds(610, 140, 50, 14);

        jLabel10.setText("Comentários:");
        add(jLabel10);
        jLabel10.setBounds(490, 170, 80, 14);

        lblCadastro.setText("Ainda não é cadastado? Cadastre-se já!");
        lblCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroMouseClicked(evt);
            }
        });
        add(lblCadastro);
        lblCadastro.setBounds(55, 200, 210, 14);

        lblComentarios.setText("0");
        add(lblComentarios);
        lblComentarios.setBounds(610, 170, 50, 14);
        add(edUsuario);
        edUsuario.setBounds(110, 90, 140, 20);
        add(edSenha);
        edSenha.setBounds(110, 120, 140, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMouseClicked
        this.parent.changePanel(Santanbooks.REGISTER);
    }//GEN-LAST:event_lblCadastroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField edBusca;
    private javax.swing.JPasswordField edSenha;
    private javax.swing.JTextField edUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblLivros;
    private javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables

}
