package Programa.Santanbooks.src;

import javax.swing.*;
import java.awt.*;

@SuppressWarnings("serial")
public class Santanbooks extends JFrame {
    
    public static final String HOME_PAGE = "home";
    public static final String REGISTER = "register";
    
    public Santanbooks() {
        super("Santanbooks");
        setSize(800,600);
        setLocationRelativeTo(null);
        initComponents();
        
        this.addPanel(new Home(this), HOME_PAGE);
        this.addPanel(new Register(this), REGISTER);
        
        this.changePanel(HOME_PAGE);
    }
    
    public void addPanel(JPanel novo, String nome) {
        this.jpExibicao.add(novo,nome);
    }
    
    public void changePanel(String nome) {
        ((CardLayout)this.jpExibicao.getLayout()).show(this.jpExibicao, nome);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jpExibicao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Santanbooks"); // NOI18N
        setResizable(false);

        jpExibicao.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");   
                }
                catch (Exception e) {}
                
                new Santanbooks().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpExibicao;
    // End of variables declaration//GEN-END:variables
}
