/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoggedIn.java
 *
 * Created on 18/06/2011, 01:15:58
 */

/**
 *
 * @author Renato
 */
public class SessionManagerLoggedIn extends javax.swing.JPanel {
    private Santanbooks parent;
    /** Creates new form LoggedIn */
    public SessionManagerLoggedIn(Santanbooks p) {
        this.parent = p;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloLabel = new javax.swing.JLabel();
        editProfileLabel = new javax.swing.JLabel();
        addBookLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 50));
        setMinimumSize(new java.awt.Dimension(800, 50));
        setPreferredSize(new java.awt.Dimension(800, 50));
        setLayout(null);

        helloLabel.setText("Olá, <USERNAME>!");
        add(helloLabel);
        helloLabel.setBounds(620, 10, 100, 14);

        editProfileLabel.setForeground(new java.awt.Color(0, 0, 255));
        editProfileLabel.setText("Edite seu perfil");
        editProfileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(editProfileLabel);
        editProfileLabel.setBounds(620, 30, 80, 14);

        addBookLabel.setForeground(new java.awt.Color(0, 0, 255));
        addBookLabel.setText("Adicionar livro");
        addBookLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(addBookLabel);
        addBookLabel.setBounds(720, 30, 70, 14);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JLabel editProfileLabel;
    private javax.swing.JLabel helloLabel;
    // End of variables declaration//GEN-END:variables
}
