/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowUser.java
 *
 * Created on 17/06/2011, 23:19:05
 */

/**
 *
 * @author Renato
 */
public class ShowUser extends javax.swing.JPanel {
    private Santanbooks parent;
    /** Creates new form ShowUser */
    public ShowUser(Santanbooks p) {
        this.parent = p;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        personalTitle2 = new javax.swing.JLabel();
        academicTitle1 = new javax.swing.JLabel();
        bdayLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        courseLabel1 = new javax.swing.JLabel();
        collegeLabel1 = new javax.swing.JLabel();
        genderLabel1 = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24));
        jLabel1.setText("<USERNAME>");
        add(jLabel1);
        jLabel1.setBounds(320, 70, 170, 32);

        descriptionLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descriptionLabel1.setText("Sobre <USERNAME>:");
        add(descriptionLabel1);
        descriptionLabel1.setBounds(188, 242, 117, 14);

        nameLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        nameLabel2.setText("Nome:");
        add(nameLabel2);
        nameLabel2.setBounds(191, 150, 35, 14);

        personalTitle2.setFont(new java.awt.Font("DejaVu Sans 13 13", 1, 13));
        personalTitle2.setText("Informações pessoais:");
        add(personalTitle2);
        personalTitle2.setBounds(188, 123, 140, 16);

        academicTitle1.setFont(new java.awt.Font("DejaVu Sans 13 13", 1, 13)); // NOI18N
        academicTitle1.setText("Informações acadêmicas :");
        add(academicTitle1);
        academicTitle1.setBounds(188, 338, 166, 18);

        bdayLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        bdayLabel1.setText("Nascimento:");
        add(bdayLabel1);
        bdayLabel1.setBounds(346, 180, 70, 14);

        emailLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        emailLabel1.setText("E-mail:");
        add(emailLabel1);
        emailLabel1.setBounds(188, 210, 38, 14);

        courseLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        courseLabel1.setText("Curso:");
        add(courseLabel1);
        courseLabel1.setBounds(230, 400, 35, 14);

        collegeLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        collegeLabel1.setText("Universidade:");
        add(collegeLabel1);
        collegeLabel1.setBounds(188, 370, 77, 14);

        genderLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        genderLabel1.setText("Sexo:");
        add(genderLabel1);
        genderLabel1.setBounds(195, 180, 31, 14);

        yearLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        yearLabel1.setText("Ano:");
        add(yearLabel1);
        yearLabel1.setBounds(240, 430, 25, 14);

        jLabel2.setText("<NOME DO USUARIO>");
        add(jLabel2);
        jLabel2.setBounds(236, 150, 112, 14);

        jLabel3.setText("<SEXO>");
        add(jLabel3);
        jLabel3.setBounds(236, 180, 42, 14);

        jLabel4.setText("<NASCIMENTO>");
        add(jLabel4);
        jLabel4.setBounds(426, 180, 82, 14);

        jLabel5.setText("<EMAIL>");
        add(jLabel5);
        jLabel5.setBounds(236, 210, 46, 14);

        jLabel6.setText("<DESCRIÇAO DO USUARIO>");
        add(jLabel6);
        jLabel6.setBounds(188, 260, 142, 72);

        jLabel7.setText("<UNIVERSIDADE>");
        add(jLabel7);
        jLabel7.setBounds(277, 370, 90, 14);

        jLabel8.setText("<CURSO>");
        add(jLabel8);
        jLabel8.setBounds(275, 400, 51, 14);

        jLabel9.setText("<ANO>");
        add(jLabel9);
        jLabel9.setBounds(275, 430, 38, 14);

        jButton1.setText("Voltar");
        add(jButton1);
        jButton1.setBounds(360, 480, 61, 23);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicTitle1;
    private javax.swing.JLabel bdayLabel1;
    private javax.swing.JLabel collegeLabel1;
    private javax.swing.JLabel courseLabel1;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel personalTitle2;
    private javax.swing.JLabel yearLabel1;
    // End of variables declaration//GEN-END:variables
}
