/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowUser.java
 *
 * Created on 17/06/2011, 23:19:05
 */

/**
 *
 * @author Renato
 */
public class ShowUser extends javax.swing.JPanel {
    private Santanbooks parent;
    /** Creates new form ShowUser */
    public ShowUser(Santanbooks p) {
        this.parent = p;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        personalTitle2 = new javax.swing.JLabel();
        academicTitle1 = new javax.swing.JLabel();
        bdayLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        courseLabel1 = new javax.swing.JLabel();
        collegeLabel1 = new javax.swing.JLabel();
        genderLabel1 = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("<USERNAME>");

        descriptionLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        descriptionLabel1.setText("Sobre <USERNAME>:");

        nameLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        nameLabel2.setText("Nome:");

        personalTitle2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        personalTitle2.setText("Informações pessoais:");

        academicTitle1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        academicTitle1.setText("Informações acadêmicas :");

        bdayLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        bdayLabel1.setText("Nascimento:");

        emailLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailLabel1.setText("E-mail:");

        courseLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        courseLabel1.setText("Curso:");

        collegeLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        collegeLabel1.setText("Universidade:");

        genderLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        genderLabel1.setText("Sexo:");

        yearLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        yearLabel1.setText("Ano:");

        jLabel2.setText("<NOME DO USUARIO>");

        jLabel3.setText("<SEXO>");

        jLabel4.setText("<NASCIMENTO>");

        jLabel5.setText("<EMAIL>");

        jLabel6.setText("<DESCRIÇAO DO USUARIO>");

        jLabel7.setText("<UNIVERSIDADE>");

        jLabel8.setText("<CURSO>");

        jLabel9.setText("<ANO>");

        jButton1.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(personalTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nameLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(genderLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addComponent(bdayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(descriptionLabel1)
                    .addComponent(jLabel6)
                    .addComponent(academicTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(collegeLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(courseLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(yearLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton1)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(personalTitle2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel2)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel1)
                    .addComponent(jLabel3)
                    .addComponent(bdayLabel1)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(academicTitle1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(collegeLabel1)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseLabel1)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearLabel1)
                    .addComponent(jLabel9))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicTitle1;
    private javax.swing.JLabel bdayLabel1;
    private javax.swing.JLabel collegeLabel1;
    private javax.swing.JLabel courseLabel1;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel personalTitle2;
    private javax.swing.JLabel yearLabel1;
    // End of variables declaration//GEN-END:variables
}
